# Update homebrew and upgrade any packages
update
upgrade

# Install some basics
install wget --enable-iri
install coreutils
install moreutils
install findutils
install gd --universal
install libjpeg --universal
install libpng --universal
install ImageMagick --with-ghostscript

# Useful stack tools
install autoconf
install node
install git
install gmp
install openssl
install nginx

# Useful DBs
install mysql
install redis
install mongodb

cleanup
